### ISSUE TITLE
Improve handling of dependency graphs

### ISSUE THREAD

**Issue by mnonnenmacher** [oss-review-toolkit/ort#4069]
Currently some package managers store their dependencies as dependency tree, and some use the dependency graph. The goal is that all package managers should use the dependency graph representation.

As converting a package manager to natively create the new format takes some effort, as a first step convert the dependency trees after running the package managers and later convert them one by one to support the new graph representation.

Also, currently it is required to call the `AnalyzerResult.withResolvedScopes()` function to make sure that the `scope` properties of the `Project`s are properly initialized. This can lead to wrong results if the user forgets to call that function. To eliminate the need for calling that function, identify which code is currently using the `Project.scope` property and provide an alternative API with the same functionality but which operates on the dependency graphs. The benefit is that converting the graphs to trees to initialize the scopes uses more memory because the same data exist in two separate representations, providing an API on top of the graphs eliminates that issue.

The implementation should be backward compatible so that old ORT result files that use the dependency tree representation can still be deserialized.

**Comment by oheger-bosch** [comment]
I did a search for code using the `Project.scopes` property. Find the full list of references with short remarks below.

While some of these references are pretty easy to convert, there is the general problem that the API of dealing with the dependencies in an `OrtResult` is often tight to a concrete implementation - namely the data classes `Project`, `Scope`, and `PackageReference`. At least the latter two are not used by the dependency graph representation. So I think in order to provide an alternative API for these clients, there needs to be some kind of abstraction or a different approach (e.g. operate on scope names rather than `Scope` objects; provide functions that return the identifiers of the dependencies of a specific package rather than dealing with a `PackageReference` etc.)

To make this new API more explicit, do you think it is worth to introduce a dedicated interface for this purpose? Maybe something like `DependencyHandler`?

Here are the current usages of the `Project.scopes` property:

- Project
  - collectDependencies(): Set<Identifier>
  - collectIssues(): Map<Identifier, Set<OrtIssue>>
  - collectSubProjects(): Set<Identifier>
  - findReferences(): List<PackageReference>
- OrtResult
  - packages: Map<Identifier, PackageEntry>
- RuleSet
  - execution of dependency rules, which get initialized with a package, a package reference, the list of ancestors
- GenerateScopesExcludesCommand
  - filters over scope names
- RemoveEntriesCommand
  - collects all scope names
- ProjectAnalyzerResult
  - collectIssues(): Map<Identifier, OrtIssue>
  - collectPackagesByScope(): List<Package>
- EvaluatedModelMapper
  - createExcludeInfo() iterate over all dependencies
  - createScopes() determine all scope names
  - addDependencyTree() iterate over all scopes and their dependencies
  - addShortestPaths() uses Scope.getShortestPaths()
- ReportTableModelMapper()
  - getScopesForDependencies() iterate over all scopes and their dependencies
- StatisticsCalculator
  - getTreeDepth() query depths of dependency trees over all scopes
  - getIncludedScopes() iterate over all scopes and collect their names
  - getExcludedScopes() iterate over all scopes and collect their names

**Comment by oheger-bosch** [comment]
As there has not been that much feedback, I have created a number of (draft) pull requests to address several sub tasks of this ticket. These PRs depend on each other, which unfortunately cannot be avoided; so they should be reviewed and merged in order:

- [ ] #4166 introduces an API to access dependency information from an ORT result and modifies a number of clients to use this API; this is ready for review
- [ ] #4209 addresses the remaining clients of dependency information and converts them to the new API
- [ ] #4244 implements the API to access dependency information for the dependency graph format

**Comment by oheger-bosch** [comment]
#4480 was the last PR related to this ticket; with it being closed, I think this ticket is done as well. Or do you think there is some more to be done @sschuberth @mnonnenmacher @fviernau ?

**Comment by fviernau** [comment]
Regarding dependency graph I have two things which are not clear to me, but I'm not saying these need to be in scope of this ticket. Just to share it
1. Cycles
   a. Several client code locations of dependency graph / navigator assume that there is no cycle in the graph
       should we have a ticket to allow cycles in the graph and to remove these assumption
   b. in case we opt for no cycles in graph: Shall we keep on using the cycle removal I added and eliminate all cycle removal related logic from each respective package manager?
   c. I could not find any documentation about how cycles are handled or what the plans are, neither are there tests IIUC
2. Using dependency graph builder for multiple unrelated projects
   a. I haven't understood whether using a single builder instance for multiple unrelated projects with overlapping package IDs would lead to issues.

**Comment by oheger-bosch** [comment]
Regarding 2: When using a shared builder instance to process multiple projects, only a single dependency graph is created. Packages that are referenced by multiple projects are added only once to the resulting graph (provided that they have the same set of transitive dependencies; otherwise, they can occur multiple times).

Or what do you mean by overlapping package IDs?

**Comment by fviernau** [comment]
> Or what do you mean by overlapping package IDs?

I meant, equal `Identifier`s ?

**Comment by oheger-bosch** [comment]
So did I answer your question or did I understand you wrong?

**Comment by fviernau** [comment]
> So did I answer your question or did I understand you wrong?

Not really, I believe my underlying thinking was

I was wondering if using a single builder instance for all projects of any given type (1) is recommended or even (2) is a must, or (3) needs to be decided case by case. If (3) in which cases can it lead to problems and to what kind of problems.

**Comment by oheger-bosch** [comment]
Thanks for clarifying. Well, in the current implementation, I would actually say it is a must to use a single builder instance to create a shared dependency graph for all the definition files processed by a `PackageManager` implementation. This is due to the fact that an analyzer result contains a map of dependency graphs keyed by the package manager name - so there can be only a single graph per package manager. This is also the most efficient solution, since all redundancies in dependencies can be eliminated.

Thinking about this, it may be beneficial to provide an abstract `PackageManager` base class for managers using the dependency graph format. This base class could manage the shared builder instance and create the final, combined dependency graph - although, this logic is not really complicated.

**Comment by sschuberth** [comment]
> Thinking about this, it may be beneficial to provide an abstract `PackageManager` base class for managers using the dependency graph format.

I like this. Historically, we gave very little guidance on how Package Managers should be implemented. Sounds good if we could give more guidance / reduce code duplication here, by introducing maybe even several "template" classes to derive from / implement for different typical scenarios, like calling CLI tools, parsing lock files etc.

**Comment by sschuberth** [comment]
What's still left to do here @mnonnenmacher, @oheger-bosch?

**Comment by oheger-bosch** [comment]
Regarding cycles in dependency graphs: All the package managers I have converted to the new format so far had a logic to detect cycles in their dependencies and to eliminate them. I think, this is necessary to prevent them from entering infinite loops, but this is nowhere documented either. Because of this, the graphs produced by the current implementation should actually be free of cycles.

So one option to handle this issue could simply be to document that it is in the package manager's responsibility to skip cycles in the graph. From what I have seen so far, this seems to reflect reality.

**Comment by oheger-bosch** [comment]
> 
> 
> What's still left to do here @mnonnenmacher, @oheger-bosch?

From my POV, all acceptance criteria of this ticket have been addressed. It can therefore be closed.

@fviernau has put some interesting, related questions, but if he agrees, these could be handled in more specific follow-up tickets.

**Comment by sschuberth** [comment]
> So one option to handle this issue could simply be to document that it is in the package manager's responsibility to skip cycles in the graph.

I'm wondering whether there'd also be a way to move this to some "common logic" so not every package manager has to implement this by itself.

**Comment by oheger-bosch** [comment]
> 
> I'm wondering whether there'd also be a way to move this to some "common logic" so not every package manager has to implement this by itself.

Not sure whether this is possible in general, since concrete package manager implementations typically navigate their specific dependency representations, and the logic to detect cycles is integrated in this navigation. In `Gradle` for instance, it is part of the Groovy script that gets injected into the build.

One option could be to let `DependencyGraphBuilder` check for cycles when new dependencies are added. But this needs some investigation, how it could be integrated with the navigation logic of package managers.

**Comment by fviernau** [comment]
> I'm wondering whether there'd also be a way to move this to some "common logic" so not every package manager has to implement this by itself.

I was also wondering that. @oheger-bosch  is right that the package manager needs to take of preventing infinite loops, however the detection of this might be possible to move to a common place. Maybe as simple as

```
// returns true if adding this edge closed a cycle.
fun Graph.addEdge(val from, val to): Boolean {

}
```
Haven't thought about whether an efficient implementation of this is actually possible.

**Comment by fviernau** [comment]
> @fviernau has put some interesting, related questions, but if he agrees, these could be handled in more specific follow-up tickets.

Sure, I agree.
