### ISSUE TITLE
Epic about using custom / newer ScanCode versions

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#4631]
Currently, the ScanCode version to use is [hard-coded](https://github.com/oss-review-toolkit/ort/blob/5fc30626d26e1be1c618525a912a3da055460c15/gradle.properties#L88) in ORT. This tight coupling prevents mixing of arbitrary ORT / ScanCode versions, and hinders a fast / user-specific upgrade of ScanCode (also see #4296).

To solve this, the following things would need to be addressed:
- [x] Improve the boostrapping of scanners:
  - [x] Accept a scanner in any version, as long as it is present on the system (leaving it to the user to install a compatible version; also see #4582); see https://github.com/oss-review-toolkit/ort/pull/4669
  - [x] Bootstrap to a cached location for reuse (like done for Flutter; also see #1580).
  - [x] ~~Alternatively: Remove bootstrapping for scanners completely. However, that would requite CI to always install all supported scanners, and not only those whose tests are actually run.~~
- [x] Improve handling of license texts (also see [this comment](https://github.com/oss-review-toolkit/ort/issues/4296#issuecomment-952644016)):
  - [x] Refactor the `utils/core` module so that `utils/spdx` can depend on non-ORT-specific parts of it (the plan is to introduce `utils/common`; see https://github.com/oss-review-toolkit/ort/pull/4647, https://github.com/oss-review-toolkit/ort/pull/4652, https://github.com/oss-review-toolkit/ort/pull/4670, https://github.com/oss-review-toolkit/ort/pull/4671)
  - [x] Read license texts from the ScanCode version in use rather than embedding them, see #4523.
- [x] Verify that the [scanner criteria](https://github.com/oss-review-toolkit/ort/blob/master/scanner/src/main/kotlin/ScannerCriteria.kt) for looking up stored scan results can be configured flexible enough to e.g. declare ScanCode results of all versions from 3.2.1-rc2 to 30.1.0 as compatible:
  - [x] #3247
  - [x] ~~#3223~~
- [x] Make the ScanCode version in the Docker image easily configurable (see #4721)

### FAQ

Why not just always use the latest version of ScanCode in ORT?
- Different findings might render existing package configurations invalid.
- Expensive testing might be required.

**Comment by maxhbr** [comment]
#1580 is closed. Does that mean that all boxes in "Improve the boostrapping of scanners" can be checked?

**Comment by sschuberth** [comment]
> #1580 is closed. Does that mean that all boxes in "Improve the boostrapping of scanners" can be checked?

Yes, thanks for the reminder, done.

**Comment by mnonnenmacher** [comment]
@sschuberth Don't you think we can close this epic as the two open tickets are not required for choosing a custom ScanCode version?

**Comment by sschuberth** [comment]
Agreed. #3247 is anyway n/a anymore by now, and #3223 should not block / be part of this epic.
