### ISSUE TITLE
Improve the SCANOSS integration in ORT

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#6672]
There currently only is a basic integration of SCANOSS in ORT. The following issues should be addressed for a proper integration:

- [ ] Avoid the dependency on the [deprecated SCANOSS Java client](https://github.com/scanoss/scanner.java) and exclusively use [ORT's own client](https://github.com/oss-review-toolkit/ort/tree/main/clients/scanoss)
  - [ ] Reimplement the [Winnowing](https://theory.stanford.edu/~aiken/publications/papers/sigmod03.pdf) algorithm ([Java](https://github.com/scanoss/scanner.java/blob/master/src/main/java/com/scanoss/scanner/Winnowing.java), [Python](https://github.com/scanoss/scanoss-winnowing.py), [C](https://github.com/scanoss/wfp)) in Kotlin
  - [ ] Reimplement Blacklisting logic
  - [ ] Find a way to query the SCANOSS server version
- [x] https://github.com/oss-review-toolkit/ort/issues/3265
- [ ] Maybe: https://github.com/oss-review-toolkit/ort/issues/4088
- [ ] Create a new report with snippet-specific information (probably just generalize [fossid_snippet.ftl](https://github.com/oss-review-toolkit/ort/blob/main/plugins/reporters/fossid/src/main/resources/templates/asciidoc/fossid_snippet.ftl))

**Comment by sschuberth** [comment]
> > Find a way to query the SCANOSS server version
> 
> Hey @scanossjs, @eeisegn, is there currently an API endpoint for that?

Or @scanossjeronimo maybe?

**Comment by sschuberth** [comment]
The new plan is to address this differently, my migrating from https://github.com/scanoss/scanner.java to https://github.com/scanoss/scanoss.java as a client, replacing ORT's own one.
