### ISSUE TITLE
Report file findings in SpdxDocuments / support complete file listings in SBOMs 

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6945]
MVP: The `SpdxDocumentReporter` can (optionally) output license and copyright findings including
           file locations and the (mandatory) file hash as `SHA1`.

To implement this it makes sense to integrate a file listing for all scanned provenances into `OrtResult`. Properly doing
that (without adding too much redundancy) in turn requires to refactor the scan result representation in `OrtResult` to:

1. Store scan results by their provenance (not anymore by `id`).
2. Store file listings (path + `SHA1`) only once, also by their provenance.

The plan for the implementation is as follows:

- [x] https://github.com/oss-review-toolkit/ort/issues/6943
- [x] https://github.com/oss-review-toolkit/ort/issues/5950
- [x] https://github.com/oss-review-toolkit/ort/issues/7192
- [x] https://github.com/oss-review-toolkit/ort/issues/7206
- [x] https://github.com/oss-review-toolkit/ort/issues/6944
- [x] https://github.com/oss-review-toolkit/ort/issues/6947
- [x] https://github.com/oss-review-toolkit/ort/issues/6948

bugs:
- [x] https://github.com/oss-review-toolkit/ort/issues/7225
- [x] https://github.com/oss-review-toolkit/ort/issues/7231
- [x] https://github.com/oss-review-toolkit/ort/issues/7263

follow-ups:
- [ ] https://github.com/oss-review-toolkit/ort/issues/7155

Some potential future scanner improvements I've found whilst working on this epic:

1. If a Git-Repo manifest maps a Git repository to the root dir, then ORT returns VcsType.Git while it should be
    VcsType.GitRepo for the root provenance.
2. Cached Provenance resolution results may be outdated, so it may happen that provenance
    Resolution results are successful while the scanner can not download. Causes can be,
    - server no more available
    - revision no more available (force-push)
    - network hick-ups
    In that case we should at least have an issue reporter. It probably makes sense to re-resolve provenance in that
   case.
3. Provenance resolution could stop rely on recursive cloning, as performance improvement.
4. In case of GitRepo, the data model for the subrepositories is not always sufficient to tell which
    repository is a sub-repository. In particular, if the repo manifest maps one git repo under a sub directory of another.
5. Not verified: On the first glance it seems that for git repo, everything is scanned twice. One scan for the GitRepo
    provenance covering all git repositories and then seperate scans for all git repositories.

**Comment by fviernau** [comment]
Closing as done, because all implementation work is done and all known bug (linked in description) are fixed.
