### ISSUE TITLE
Improve ORT's documentation

### ISSUE THREAD

**Issue by tsteenbe** [oss-review-toolkit/ort#7793]
Creating this ticket to provide an overview of all tickets part of larger effort to improve ORT's documentation

Below listed issues are not listed in any specific order

- [] https://github.com/oss-review-toolkit/ort/issues/6008
- [] https://github.com/oss-review-toolkit/ort/issues/4629
- [] https://github.com/oss-review-toolkit/ort/issues/1236
- [] https://github.com/oss-review-toolkit/ort/issues/4219
- [] https://github.com/oss-review-toolkit/ort/issues/4636
- [] https://github.com/oss-review-toolkit/ort/issues/7781
- [] https://github.com/oss-review-toolkit/ort/issues/4298

**Comment by sschuberth** [comment]
FYI, there's a new IntelliJ plugin from JetBrains called [Writerside](https://plugins.jetbrains.com/plugin/20158-writerside) which might become useful here.

**Comment by sschuberth** [comment]
@tsteenbe I guess #7725 should not be in the task list, or?

**Comment by sschuberth** [comment]
Maybe https://opensource.googleblog.com/2025/05/introducing-new-open-source-documentation-resources.html could become of use here.
