### ISSUE TITLE
Problems with contradicting use-cases for SPDX documents

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#8788]
This is an umbrella issue to collect all issues that are related to different use-cases for SPDX documents and / or implied any semantics that might be conflicting:

```[tasklist]
- [ ] https://github.com/oss-review-toolkit/ort/issues/4505
- [ ] https://github.com/oss-review-toolkit/ort/issues/5483
- [ ] https://github.com/oss-review-toolkit/ort/issues/6245
```
